version: '3'
services: 
  web: 
    build: 
      #separate build context (directory) and the compose file
      context: . 
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    volumes: 
      - /app/node_modules
      - ./:/app
  tests:
    build: 
      #separate build context (directory) and the compose file
      context: . 
      dockerfile: Dockerfile 
    volumes: 
      - /app/node_modules
      - ./:/app     
    command: ["npm", "run", "test"]  
